# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: xxxxx
  open_stack:
    #copied from Bluemix
    "auth_url": "https://identity.open.softlayer.com"
    "project": "object_storage_xxx"
    "projectId": "xxxx"
    "region": "dallas"
    "userId": "xxx"
    "username": "admin_xxx_xxx"
    "password": "xxx"
    "domainId": "xxx"
    "domainName": "123456"


staging:
  secret_key_base: xxx

test:
  secret_key_base: xxx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'xxx' %>
  open_stack:
    "auth_url": "https://identity.open.softlayer.com"
    "project": "object_storage_xxx"
    "projectId": "xxxx"
    "region": "dallas"
    "userId": "xxx"
    "username": "admin_xxx_xxx"
    "password": "xxx"
    "domainId": "xxx"
    "domainName": "123456"
